### ISSUE TITLE
The input file data format is not accepted.

### ISSUE THREAD

**Issue by suyouR** [raeslab/omixer-rpm#10]
Hi!
After I used HUMAnN3 to annotate the metagenome, I obtained two formats of KO annotation results: one is presented in the form of RPK (reads per kilobase), the other is relative abundance data after the RPK data is normalized. I tried to use relative abundance data to run Omixer-RPM using the [GMM Database], but there were no results. I would like to know whether I can use relative abundance data to run, and how should I convert my data to meet the right format?

**Comment by omixer** [comment]
Hi @suyouR,

You can use the relative abundance or the RPKs but please make sure they are formatted correctly, and as described here https://github.com/raeslab/omixer-rpm?tab=readme-ov-file#input-file-format.

Best regards,
Youssef
