### ISSUE TITLE
Low % of uniref90 genefamilies mapped to KOs

### ISSUE THREAD

**Issue by qutkat** [raeslab/omixer-rpm#11]
Hi there,

I was planning to use KO annotations in HUMAnN3 to feed into omixer-rpm, but when I do this only about 4% of reads are mapping to KOs and the rest are ungrouped. I'm just wondering if this was your experience when you used this method, and if there are any alternatives for mapping to KOs more successfully?

Many thanks,
Katherine

**Comment by omixer** [comment]
Hi,

 I am not sure why you get only 4 % of reads mapped.  Did you ask this question on the  HUMAnN3 forum?
