### ISSUE TITLE
GBM detection in a species genome 

### ISSUE THREAD

**Issue by qutkat** [raeslab/omixer-rpm#12]
Hello,
Just trying to figure out how I could use omixer to detect the presence of GBMs in a particular species. If I was just looking to produce the coverage file could I load a table with the KOs present in the species genome as opposed to the sample metagenome? Would it work if I just included presence/absence data (0/1) as opposed to abundances of the KOs within the genome? 

Thanks,

Katherine

**Comment by omixer** [comment]
Hi Katherine,

Presence/absence data would work here as well. For instance, a module with 4 steps out of 5 are present will have a coverage of 80% with abundance or presence/absence data. If the module coverage cutoff is set at 70%, the module will be present. If it is set at 100% the module will be absent.

Hipe this helps
