### ISSUE TITLE
The execution of Omixer-RPM returned a non-zero exit status. 

### ISSUE THREAD

**Issue by saharbagheri** [raeslab/omixer-rpm#13]
Hi,

I'm trying to use my stratified data and see which bacteria produces which GBM/GMM. However when I run the following code I receive this error:

GBMs <- omixerRpm::rpm(x = KOs_final, module.db = db,annotation=2)

Error: "The execution of Omixer-RPM returned a non-zero exit status. Refer to the exception output for details."

I was wondering if my input should have a specific format. I tried having only a column called Gene_Family (including KOs and taxonomy) and also having two separate columns called KOs and species and in both cases I received the same error.

Thanks

**Comment by omixer** [comment]
@saharbagheri This is related to the Omixer-rpmR R package. Please check my answer there!
