### ISSUE TITLE
where is go mixer?

### ISSUE THREAD

**Issue by andressanchez1** [raeslab/omixer-rpm#4]
Hi! 
I was working with go-mixer for a paper but I cant enter/find the link. By any chance is there a new link?
Thanks in advance

**Comment by omixer** [comment]
The link is the same but the sever seems to be down! I asked the sysadmin to take a look. I will let you know as soon as it is back online! Sorry for the inconvenience!

**Comment by omixer** [comment]
It is live gain at http://www.raeslab.org/omixer/
