### ISSUE TITLE
GBM module IDs

### ISSUE THREAD

**Issue by hh1985** [raeslab/omixer-rpm#5]
Hi, @raeslab @omixer 

Some GBM modules are mixed with different types of IDs, e.g.
```
134 MGB036  S-Adenosylmethionine (SAM) synthesis
135 K00789  TIGR01034   bactNOG02937
```
Just wonder what's the recommended way to utilize the module?  Should I extract the sequences of each IDs into a fasta file, and mapped the reads into the sequences?  

Thanks,

-Han

**Comment by omixer** [comment]
Hi @hh1985,

Before you can use the modules you have to generate a count table, for example by mapping your sequencing reads on a gene catalog like the IGC (https://db.cngb.org/microbiome/genecatalog/genecatalog_human/) which has KO annotation etc...

Once you have the table please refer to the README for generating module counts from the counts table!

Best regards,
Youssef
