### ISSUE TITLE
Calculation of module abundance when coverages of the module are the same in different ways of calculation

### ISSUE THREAD

**Issue by BangzhuoTongUU** [raeslab/omixer-rpm#8]
Hi, thank you so much for develop and maintain this tool. And I have a question regarding on the calculation of module abundance. Say there is a module **M**, it includes two steps for a complete process. In the definition style of GBM database, it might be defined as:

**///
M	Some useful module
K123	NOG456
K789
///**

So the abundance of **M** can be calculated from either one of:
1. Average(K123, K789)
2. Average(NOG456, K789)
depending of whichever calculation has higher coverage

My question is: 

- What if the coverages of the two calculation are equal, but the average abundance of the module is not the same, then which abundance/calculation will OMIXER-RPM use.
- What if K123 and NOG456 are the same gene, but they are just two different ID due to different naming system from different databse, which abundance/calculation will OMIXER-RPM use? Wouldn't that cause duplication of calculation?

Look forward to your reply! Thanks!

Best,

Ben

**Comment by omixer** [comment]
Hi Ben,

For question 1, if the coverage is equal, the pathway with the highest abundance is selected, as explained in the last section of the description https://github.com/raeslab/omixer-rpm#description.

For question 2, Omixer-RPM would not know about this. This will generate 2 duplicated paths with the same coverage and abundance. Omixer-RPM will select one of them randomly if they qualify as best output.
In this case, the ortholog abundance won't be counted twice, if this is your question.

Please do not hesitate to ask if you have any further questions!

Best regards,
Youssef
